---
- hosts: workers
  become: yes

  tasks:

    # Step 1: Install Docker
    - name: Install required packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    # Step 2: Install Docker Compose
    - name: Download Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # Step 3: Create the docker-compose.yml file
    - name: Create docker-compose.yml
      copy:
        src: ./ansible_docker.yaml
        dest: /home/ubuntu/ansible_docker.yaml
        mode: '0644'
      notify:
        - Start Docker Compose

    # Step 4: Add the current user to the Docker group
    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

  handlers:
    - name: Start Docker Compose
      command: docker-compose -f /home/ubuntu/ansible_docker up -d
      args:
        chdir: /home/ubuntu/
